# Production settings
baseURL = "https://yanglinzhao.com/"
languageCode = "en-us"
title = "Yanglin Zhao"

# Asset directory
assetDir = "."

# Development settings
disableLiveReload = true

# Url settings
[permalinks]
  post = "/:slug/"

# Custom params
[params]
  DefaultAuthor = "Yanglin Zhao"
