version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run build
          command: yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - public

  deploy_static:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install netlify cli
          command:
            wget -qO- 'https://cli.netlify.com/download/latest/linux' | tar xz
      - run:
          name: Deploy to netlify
          command: ./netlifyctl -A $NETLIFY_AUTH_TOKEN -b public -y deploy

workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy_static:
          requires:
            - build
          filters:
            branches:
              only: master
